[#789] update amr mode local planning algorithm.
LexxPluss/navigation pull request #26
Opened 2022-03-07 08:30 UTC by yakato-jun

LexxPluss/LexxAuto#789 対応
新しくplanを受け取ったタイミングで、停止状態（速度及び角速度がしきい値以下の場合）の時に、その場回転してから目的地へ向かう。
アクチュエータが上がっている場合と、上がっていない場合で、それぞれその場回転する/しないをパラメータで設定可能。
その場回転の向き先は、パスプランの手前から参照して、1m(パラメータで調整可能)を超えるWaypointの方向へ向く。

2022-03-08 00:49 UTC, kokosabu requested changes

2022-03-08 00:49 UTC, kokosabu commented on dwa_local_planner/src/dwa_planner_ros.cpp
> +      double tarn_turget_th = std::atan2(tarn_turget_y - current_y, tarn_turget_x - current_x);
tarnはturnのtypoではないでしょうか?

2022-03-08 00:49 UTC, kokosabu commented on dwa_local_planner/include/dwa_local_planner/dwa_planner_ros.h
> +      bool use_rotate_first_actuator_low_;
リニアアクチュエータのHigh/Lowではなく、アクチュエータの接続/非接続や、牽引/非牽引の時に回転する/しないという表現にしたいです。

2022-03-10 10:43 UTC, yakato-jun commented on dwa_local_planner/src/dwa_planner_ros.cpp
> +      double tarn_turget_th = std::atan2(tarn_turget_y - current_y, tarn_turget_x - current_x);
紛れもなくスペルミスしております。

2022-03-10 10:47 UTC, yakato-jun commented on dwa_local_planner/include/dwa_local_planner/dwa_planner_ros.h
> +      bool use_rotate_first_actuator_low_;
アクチュエータの Connect/Disconnect にしておきます。

2022-03-10 12:49 UTC, kokosabu approved these changes

2022-03-10 12:50 UTC, merged