1321 recovery behavior
LexxPluss/navigation pull request #40
Opened 2022-05-20 06:10 UTC by remmaTech12

リカバリー時の挙動を整理しました。元々7回safety_direction_recoveryを実行（実行中にpathを見つけたらリカバリー終了）としていたのですが、以下のような問題がありました。
- 7回連続でsafety_direction_recoveryを実行するのは冗長
- 自己位置ずれの際は、safety_direction_recoveryよりも回転してリカバリした方が効果的
- safety_direction_recoveryのあとにgo_back_recoveryとrotate_small_recoveryをしていたが、safety_direction_recoveryの方が効果的なので冗長。

そこで、以下のシーケンスを3回繰り返すように整理しました。
1. 2回safety_direction_recovery（もしくはgo_back_recoveryとrotate_small_recovery）を実行
2. rotate_recoveryの実行

2022-05-20 06:48 UTC, kokosabu requested changes

2022-05-20 06:48 UTC, kokosabu commented on move_base/src/move_base.cpp
> +          safety_direction->initialize("safety_direction_recovery", &tf_, planner_costmap_ros_, controller_costmap_ros_);
initalizeはループの外に置いた方が良いのでは。
実害はないと思いますが、エラーメッセージが出力されます。
https://github.com/LexxPluss/navigation/blob/eb4641138aa1c19b5c534333012eeb950a7f4e5d/safety_direction_recovery/src/safety_direction_recovery.cpp#L133

他のinitializeしているリカバリ時の振る舞いはどれも同じことがいえます。

2022-05-20 06:48 UTC, kokosabu commented on move_base/src/move_base.cpp
> -      recovery_behaviors_carrying_.push_back(cons_clear);
継続的に消す(かつ、オプションとしても考えない)のであれば、
https://github.com/LexxPluss/navigation/blob/eb4641138aa1c19b5c534333012eeb950a7f4e5d/move_base/src/move_base.cpp#L1202-L1203
のあたりも消すなど、併せて手を入れたい。

2022-05-20 09:04 UTC, remmaTech12 commented on move_base/src/move_base.cpp
> -      recovery_behaviors_carrying_.push_back(cons_clear);
現状、以下でコストマップクリアをCLEARINGモードのときに常に呼んでいるため、上記のrecoveryは不要かとも思いますが、
```
MoveBase::clearCostmaps();
```
将来的により柔軟にcostmap clear recoveryをしたいと思ったとき（たとえばreset_distanceでクリアする距離を決めたり）にこのrecoveryが必要になるかもなと思いました。

一応残しておきたいのですが、以下のcommitの対応でいかがでしょうか？

2022-05-20 09:07 UTC, remmaTech12 commented on move_base/src/move_base.cpp
> +          safety_direction->initialize("safety_direction_recovery", &tf_, planner_costmap_ros_, controller_costmap_ros_);
ありがとうございます。対応済み。
8467c6a64f78d894cabaf0fc82850aa38d6bf00c

2022-05-23 01:56 UTC, kokosabu approved these changes

2022-05-23 01:59 UTC, kokosabu commented on move_base/src/move_base.cpp
> -      recovery_behaviors_carrying_.push_back(cons_clear);
OKです。
( `aggressive_clearing_map_allowed`と`conservative_clearing_map_allowd`両方をtrueにしたときに、コストマップクリアとコストマップクリアの間にリカバリ動作が無いのはちょっと気になりました。 )

2022-05-23 01:59 UTC, merged