303 footprint
LexxPluss/navigation pull request #8
Opened 2021-03-02 09:57 UTC by nobunoby

動きました

2021-03-03 02:17 UTC, kokosabu requested changes
コメント確認お願いします。
あと全体的に編集途中のコードをコメントで残している箇所が見受けられます。
復活させる可能性があるコードや、デバッグで使用するコードを残すことまで禁止するつもりはないですが、今となっては残しておく必要のないコードがあると思います。

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/include/costmap_2d/costmap_2d_ros.h
> +#include<geometry_msgs/Point32.h>
#include と < の間にスペース入れましょうか。

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/include/costmap_2d/footprint.h
> +std::vector<geometry_msgs::Point> makeFootprintFromParams(ros::NodeHandle& nh);//, std::string& actuator_state);
ここは実質変えてないので、もとのコードに戻しましょうか。
変更したファイルは少ない方が望ましいです。

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/src/costmap_2d_ros.cpp
> +#include<std_msgs/Int32.h>
スペース入れましょう。

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/src/costmap_2d_ros.cpp
> +  static ros::NodeHandle footprint_nh = private_nh;
未使用みたいなので削除しましょう。

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/src/costmap_2d_ros.cpp
> +
上記条件に当てはまらない場合のreturnが無い。
空のpointsを応答するとか?

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/src/costmap_2d_ros.cpp
> +    }
インデントが崩れているので揃えてください。

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/src/costmap_2d_ros.cpp
> +    }
インデントが崩れているので揃えてください

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/src/costmap_2d_ros.cpp
> +  nh.getParam("footprint", footprint_xmlrpc);
load_extended_footprintとの違いがここだけなので、load_extended_footprintとload_original_footprintまとめても良い気がします。

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/src/costmap_2d_ros.cpp
> +  nh.getParam("footprint", footprint_xmlrpc);
引数で"footprnt", "extended_footprint"を渡すようにして、受け取った引数でgetParamできるかと。

2021-03-03 02:17 UTC, kokosabu commented on costmap_2d/src/costmap_2d_ros.cpp
> +  if (msg.data==2)
PoCでmid2を付け加えたりしています。
他にも変える可能性はあるで、変更に耐えられるように
Int32ではなくStringでやり取りするようにしましょうか。

2021-03-03 10:16 UTC, nobunoby commented
303 branchの方でコード修正し、v3での動作確認が完了しました。

2021-03-04 01:48 UTC, kokosabu approved these changes

2021-03-04 01:48 UTC, merged